### PR TITLE
Exclude URL patterns from registry

### LINKED ISSUE #105: [feature-request]: Add option to exclude url patterns from the cache
### Description

It'd be nice to have the ability to exclude certain URL patterns from being cached.

```ts
importShim.skipRegistry = /^\/__internal__\.*/
```

I'm using the `importShim.fetch` to pre-process imports, but in my case I want to always run the pre-process step for specified URL patterns since content can be dynamically updated.

I'm happy to work on this if you think it would be a valuable contribution.

### PR DESCRIPTION
**Pull request by ifiokjr**
Closes #105

### CODE REVIEW

**Comment by ifiokjr** [comment]
I'm not sure how to run the tests, so I haven't added any at the moment. 

I'm happy to add some tests with guidance.

**Comment by guybedford** [comment]
See comment at https://github.com/guybedford/es-module-shims/issues/105#issuecomment-738518289.

**Comment by guybedford** [comment]
To run the tests run an http server locally then open test/test.html.

**Comment by guybedford** [comment]
I think a better approach to this could be to entirely not cache failed fetches, as Chrome plans to do. If you're still interested in working on this problem let me know.

**Pull request closed without merging**
