### PR TITLE
Fix issue #22

### PR DESCRIPTION
**Pull request by costingeana**

### CODE REVIEW

**Comment by guybedford** [comment]
Thanks for the fix here... you can tell how much time I've got for this project :P

@costingeana if you'd be interested in being a co-maintainer I can add you as a collaborator?

**Comment by guybedford** [comment]
Released in 0.2.10.

**Comment by costingeana** [comment]
@guybedford, I know you are busy and that this project is not your main focus. So if you think I can help then I'd be happy to be a collaborator.
As I side note...I'm already using es-module-shim (along with jspm) in a project I'm working on, therefore I'm quite interested to contribute.

**Comment by guybedford** [comment]
@costingeana thanks, I've added you as a collaborator. Please still post PRs for review. If you're interested in contributing to jspm as well, that would be great too. And just let me know if you'd like to join the Discord chat or follow the link at https://github.com/jspm/project/blob/master/CONTRIBUTING.md#discussion.

**Pull request merged**
