### PR TITLE
Fix sourcemapping regex

### PR DESCRIPTION
**Pull request by guybedford**
Resolves https://github.com/guybedford/es-module-shims/issues/217.

//cc @hronro

### CODE REVIEW

**Comment by hronro** [comment]
CleanShot 2021-11-04 at 11 31 05@2x

It's really hard to be done properly with simple regex replacement.

**Comment by guybedford** [comment]
Because they have to be at the end of the source it is actually quite well defined.

I've pushed up a new fix, let me know if that can work for you?

**Comment by hronro** [comment]
Cook, the new fix works for me.

**Comment by guybedford** [comment]
Thanks for confirming, I will include in the next release in the next few days.

**Pull request merged**
